version: '3'

services: 
    server:
        container_name: server
        build:
            context: ./server/
            dockerfile: server.Dockerfile
        ports:
            - "5000:5000"
        depends_on: 
            - postgres
    postgres:
        container_name: postgres
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: postgres
            POSTGRES_DB: knex_dev

