/**
 * @swagger
 * components:
 *  schemas:
 *     Book:
 *       type: object
 *       required:
 *          - title
 *          - author
 *       properties:
 *          id:
 *              type: string
 *              description: The autogenerated id
 *          title:
 *              type: string
 *              description: The book title
 *          author:
 *              type: string
 *              description: The book author
 *      example:
 *          id: 22
 *          title: The New
 *          author: Djon Dou
 *
 *
 * 
 */